- name: Check if Lidarr is installed
  stat:
    path: /opt/lidarr
  register: lidarr_installed

- name: Create Lidarr directory
  file:
    path: /opt/lidarr
    state: directory
    mode: '0755'
  when: not lidarr_installed.stat.exists

- name: Copy Lidarr docker-compose file
  copy:
    src: ../../../../files/docker-compose/lidarr-compose.yaml
    dest: /opt/lidarr/docker-compose.yaml
    mode: '0644'
  when: not lidarr_installed.stat.exists

- name: Run Lidarr container
  shell: docker compose up -d
  args:
    chdir: /opt/lidarr
  when: not lidarr_installed.stat.exists
