- name: Ensure required LXC features for CTs (patch on the right PVE host)
  hosts: all
  gather_facts: false


  vars:
     # Map TF node strings to SSH inventory hostnames if needed (adjust to your names)
     pve_host_aliases:
       proxmox01: proxmox01
       proxmox02: proxmox02
       pve01: pve01
       pve02: pve02



  # Load the JSON list written by deploy.sh (it's a plain array)
  tasks: 
    - name: Load ct_features array from JSON
      set_fact:
        ct_features: "{{ lookup('file', '../vars/ct_features.json') | from_json }}"

    - name: Set needed containers to use apparmor profile
      include_tasks: tasks/proxmox_lxc_set_apparmour.yml
      when: inventory_hostname in groups['docker_hosts']
      loop: "{{ ct_features }}"
      loop_control:
        loop_var: ct
        label: "{{ ct.name }}@{{ ct.node }} (ctid={{ ct.ctid }})"