#!/usr/bin/env bash
set -Eeuo pipefail

# -------- Config --------
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ANSIBLE_DIR="${REPO_ROOT}/ansible"
ANSIBLE_VARS_DIR="${ANSIBLE_DIR}/vars"
ANSIBLE_PLAYBOOKS_DIR="${ANSIBLE_DIR}/playbooks"
ANSIBLE_INV_DIR="${ANSIBLE_DIR}/inventories"

# Expected files generated by previous runs or external processes
INV_TF="${ANSIBLE_INV_DIR}/terraform.yml"
INV_PLUGIN="${ANSIBLE_INV_DIR}/proxmox.proxmox.yml"
INV_PVE="${ANSIBLE_INV_DIR}/pve_hosts.yml"

CT_FEATURES_JSON="${ANSIBLE_VARS_DIR}/ct_features.json"
CT_IPS_JSON="${ANSIBLE_VARS_DIR}/ct_ips.json"

DOTENV="${REPO_ROOT}/.env"

# Optional env
VAULT_FLAG=${VAULT_FLAG:-}

# -------- Helpers --------
fail() { echo -e "\n[ERROR] $*\n" >&2; exit 1; }
ok()   { echo -e "[OK] $*"; }
info() { echo -e "[INFO] $*"; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || fail "$1 not found in PATH."; }

# -------- Preflight --------
require_cmd ansible
require_cmd ansible-playbook
require_cmd ansible-inventory
command -v ssh-keyscan >/dev/null 2>&1 || info "ssh-keyscan not found. We'll proceed; accept-new will handle first connect."

[[ -d "${ANSIBLE_DIR}" ]] || fail "Ansible dir not found: ${ANSIBLE_DIR}"
mkdir -p "${ANSIBLE_INV_DIR}" "${ANSIBLE_VARS_DIR}" "${ANSIBLE_PLAYBOOKS_DIR}" "${ANSIBLE_DIR}/known_hosts"

# -------- Load .env --------
if [[ -f "${DOTENV}" ]]; then
  info "Loading environment from ${DOTENV}"
  set -a
  source "${DOTENV}"
  set +a
  ok ".env loaded"
else
  info "No .env found at ${DOTENV} (continuing without it)"
fi

# -------- Generate per-run known_hosts from ct_ips --------
ENV_BASENAME="ansible_run"
KNOWN_HOSTS_FILE="${ANSIBLE_DIR}/known_hosts/${ENV_BASENAME}.known_hosts"

: > "${KNOWN_HOSTS_FILE}"
if [[ -s "${CT_IPS_JSON}" ]]; then
  if command -v jq >/dev/null 2>&1; then
    HOSTS="$(jq -r 'to_entries[] | .value' "${CT_IPS_JSON}" | xargs || true)"
  else
    HOSTS="$(sed -E 's/["{} ]//g; s/,/\n/g' "${CT_IPS_JSON}" | awk -F: 'NF==2{print $2}' | xargs || true)"
  fi
  
  if [[ -n "${HOSTS}" ]] && command -v ssh-keyscan >/dev/null 2>&1; then
    info "Populating ${KNOWN_HOSTS_FILE} via ssh-keyscan for: ${HOSTS}"
    ssh-keyscan -T 3 -H -t rsa,ecdsa,ed25519 ${HOSTS} >> "${KNOWN_HOSTS_FILE}" 2>/dev/null || true
  else
    info "ssh-keyscan unavailable or host list empty."
  fi
else
  info "No CT IPs file present; known_hosts will be filled on first connect."
fi

# -------- Build inventory args --------
pushd "${ANSIBLE_DIR}" >/dev/null
INVENTORY_ARGS=()
add_inv() {
  local f="$1"
  if [[ -f "$f" ]]; then INVENTORY_ARGS+=("-i" "$f"); else info "Inventory missing (skipping): $f"; fi
}
add_inv "${INV_TF}"
add_inv "${INV_PLUGIN}"
add_inv "${INV_PVE}"

[[ ${#INVENTORY_ARGS[@]} -gt 0 ]] || fail "No usable inventories found."
info "Inventories included: ${INVENTORY_ARGS[*]}"

# -------- Deploy SSH keys to Proxmox Nodes --------
info "Deploying local SSH keys to Proxmox Nodes..."
if [[ -n "${ADMIN_PASSWORD:-}" ]]; then
  ANSIBLE_SSH_ARGS="-o UserKnownHostsFile=${KNOWN_HOSTS_FILE} -o StrictHostKeyChecking=accept-new -o LogLevel=ERROR -o PreferredAuthentications=keyboard-interactive,password,publickey" \
  ansible-playbook "${INVENTORY_ARGS[@]}" -u root --limit "proxmox01,proxmox02" \
    -e "ansible_password=${ADMIN_PASSWORD}" -e "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o LogLevel=ERROR'" \
    "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_ssh.yml" ${VAULT_FLAG} || info "SSH key deployment failed"
else
  info "ADMIN_PASSWORD not set in .env. You will be prompted to type your SSH password for the Proxmox nodes."
  ANSIBLE_SSH_ARGS="-o UserKnownHostsFile=${KNOWN_HOSTS_FILE} -o StrictHostKeyChecking=accept-new -o LogLevel=ERROR -o PreferredAuthentications=keyboard-interactive,password,publickey" \
  ansible-playbook "${INVENTORY_ARGS[@]}" -u root --limit "proxmox01,proxmox02" \
    -k -e "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o LogLevel=ERROR'" \
    "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_ssh.yml" ${VAULT_FLAG} || info "SSH key deployment failed"
fi

# -------- Bootstrap admin user on Proxmox Nodes --------
if [[ -n "${ADMIN_PASSWORD:-}" ]]; then
  info "Bootstrapping admin user on Proxmox Nodes as root..."
  ansible-playbook "${INVENTORY_ARGS[@]}" -u root --limit "proxmox01,proxmox02" \
    -e "ansible_password=${ADMIN_PASSWORD}" -e "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'" \
    "${ANSIBLE_PLAYBOOKS_DIR}/bootstrap_user.yml" ${VAULT_FLAG} || info "Node bootstrap play skipped/failed"
else
  info "ADMIN_PASSWORD not set; skipping automated Node bootstrap."
fi

# -------- Proxmox Docker Perms & Feature Patches --------
RUN_PATCH_PLAY=true
[[ -s "${CT_FEATURES_JSON}" ]] || RUN_PATCH_PLAY=false

if $RUN_PATCH_PLAY; then
  info "Patching LXC features on Proxmox hosts..."
  ansible-playbook "${INVENTORY_ARGS[@]}" "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_lxc_features.yml" ${VAULT_FLAG} || fail "CT feature patch failed"
  ok "Proxmox CT features ensured"
fi

# -------- Bootstrap admin user on CTs --------
CT_LIMIT=""
if [[ -s "${CT_IPS_JSON}" ]]; then
  if command -v jq >/dev/null 2>&1; then
    CT_LIMIT="$(jq -r 'keys | join(":")' "${CT_IPS_JSON}")"
  else
    CT_LIMIT="$(sed -E 's/["{} ]//g; s/,/\n/g' "${CT_IPS_JSON}" | awk -F: 'NF==2{print $1}' | paste -sd: -)"
  fi
fi

if [[ -n "${CT_LIMIT}" ]]; then
  info "Bootstrapping admin user on CTs (${CT_LIMIT}) as root…"
  ansible-playbook "${INVENTORY_ARGS[@]}" -u root --limit "${CT_LIMIT}" \
    -e "ansible_password=${ADMIN_PASSWORD}" -e "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'" \
    "${ANSIBLE_PLAYBOOKS_DIR}/bootstrap_user.yml" ${VAULT_FLAG} || info "Bootstrap play failed"
fi

# -------- Mounts & Services --------
declare -a PLAY_NAMES=(
  "Mounting SMB shares"
  "Adding SMB share access"
  "Installing CT pre-requisites"
  "Installing CT services"
)
declare -a PLAY_FILES=(
  "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_mount_smb_shares.yml"
  "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_lxc_share_access.yml"
  "${ANSIBLE_PLAYBOOKS_DIR}/proxmox_ct_pre-requisites.yml"
  "${ANSIBLE_PLAYBOOKS_DIR}/ct_services_docker.yml"
)

for i in "${!PLAY_NAMES[@]}"; do
  name="${PLAY_NAMES[$i]}"
  file="${PLAY_FILES[$i]}"
  info "Running: $name..."
  ansible-playbook "${INVENTORY_ARGS[@]}" "$file" ${VAULT_FLAG} || info "$name failed (continuing)"
done

ok "Done."