---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/radarr:/config
      - /mnt/media:/media
    ports:
      - 7878:7878